// server/middleware/authMiddleware.js
import passport from 'passport';

// Middleware to protect routes using JWT strategy
export const protect = (req, res, next) => {
  // Use passport.authenticate with the 'jwt' strategy
  // { session: false } because we're using tokens
  // Provide a custom callback to handle the result
  passport.authenticate('jwt', { session: false }, (err, user, info) => {
    // Handle potential errors from the strategy (e.g., DB error)
    if (err) {
      console.error("Error during JWT authentication:", err);
      return next(err); // Pass error to global handler
    }
    // Handle authentication failure (token invalid, user not found, etc.)
    if (!user) {
       console.warn("JWT Authentication failed:", info?.message || "No user found for token");
      // Customize error message based on 'info' if needed
      let message = 'Unauthorized: Invalid or missing token.';
      if (info?.name === 'JsonWebTokenError') message = 'Unauthorized: Malformed token.';
      if (info?.name === 'TokenExpiredError') message = 'Unauthorized: Token expired.';

      return res.status(401).json({ message: message });
    }

    // Authentication successful!
    // Attach the user object to the request for use in subsequent handlers
    console.log(`User authenticated via JWT: ${user.email} (${user.id})`);
    req.user = user;
    next(); // Proceed to the actual route handler (e.g., createMap)
  })(req, res, next); // Call the middleware function generated by passport.authenticate
};
