# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Dev Branch

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      env:
          CUCUMBER_PUBLISH_TOKEN: b9a5a2f7-ef61-4ce0-bded-851ec5f9bc79
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: echo "${{ env.CUCUMBER_PUBLISH_TOKEN }}"
    - run: cross-env CUCUMBER_PUBLISH_TOKEN=b9a5a2f7-ef61-4ce0-bded-851ec5f9bc79 && npm test
